"""Shared git-provenance capture for the Praxia tool family.

See the module docstrings of `record.py`, `capture.py`, `channels.py`, and
`durable.py` for the full design rationale. Public surface re-exported here.
"""

from __future__ import annotations

from .capture import (
    GIT_REPO_LOCATION_ENV_VARS,
    GitCommitInfo,
    GitResolutionError,
    abuild_provenance_record,
    acompute_dirty_content_id,
    aresolve_git_commit,
    build_provenance_record,
    clean_git_env,
    compute_dirty_content_id,
    resolve_git_commit,
)
from .channels import (
    GitState,
    capture_git_state,
)
from .durable import (
    DEFAULT_MANIFEST_RELPATH,
    DEFAULT_MAX_SNAPSHOT_BYTES,
    DEFAULT_RUN_REF_PREFIX,
    DEFAULT_WIP_REF_PREFIX,
    SNAPSHOT_FULL,
    SNAPSHOT_METADATA_ONLY,
    SNAPSHOT_NONE,
    ImportReport,
    PinResult,
    SnapshotResult,
    append_manifest,
    export_bundle,
    ignored_declared_paths,
    ignored_provenance_paths,
    import_bundles,
    manifest_candidates,
    manifest_entry,
    pin_result_as_dict,
    pin_run,
    ref_resolves,
    repo_root,
    snapshot_worktree,
    snapshot_worktree_detailed,
    uncommitted_diff_for_run,
    update_ref,
)
from .record import (
    PROVENANCE_FILENAME,
    ProvenanceRecord,
    from_env,
    read_state_record,
    state_record_path,
    to_env,
    to_json_bytes,
    write_state_record,
)

__all__ = [
    "DEFAULT_MANIFEST_RELPATH",
    "DEFAULT_MAX_SNAPSHOT_BYTES",
    "DEFAULT_RUN_REF_PREFIX",
    "DEFAULT_WIP_REF_PREFIX",
    "GIT_REPO_LOCATION_ENV_VARS",
    "GitCommitInfo",
    "GitResolutionError",
    "GitState",
    "ImportReport",
    "PROVENANCE_FILENAME",
    "PinResult",
    "ProvenanceRecord",
    "SNAPSHOT_FULL",
    "SNAPSHOT_METADATA_ONLY",
    "SNAPSHOT_NONE",
    "SnapshotResult",
    "abuild_provenance_record",
    "acompute_dirty_content_id",
    "append_manifest",
    "aresolve_git_commit",
    "build_provenance_record",
    "capture_git_state",
    "clean_git_env",
    "compute_dirty_content_id",
    "export_bundle",
    "from_env",
    "ignored_declared_paths",
    "ignored_provenance_paths",
    "import_bundles",
    "manifest_candidates",
    "manifest_entry",
    "pin_result_as_dict",
    "pin_run",
    "read_state_record",
    "ref_resolves",
    "repo_root",
    "resolve_git_commit",
    "snapshot_worktree",
    "snapshot_worktree_detailed",
    "state_record_path",
    "to_env",
    "to_json_bytes",
    "uncommitted_diff_for_run",
    "update_ref",
    "write_state_record",
]
